hydra:
  run:
    dir: ./outputs/Chapter_03/AE/${now:%Y-%m-%d}/${now:%H-%M-%S}
data:
  pin_memory: True
  num_workers: 8
  batch_size: 100
  shuffle: True
model:
  input_image_shape: [1, 32, 32]
  input_size:
    - 1
    - 32
    - 32
  encoder_number_of_channels:
    - 32
    - 64
    - 128
  encoder_kernel_sizes:
    - 3
    - 3
    - 3
  encoder_strides:
    - 2
    - 2
    - 2
  decoder_number_of_channels:
    - 128
    - 64
    - 32
  decoder_kernel_sizes:
    - 3
    - 3
    - 3
  decoder_strides:  # strides for the transposed convolutions
    - 2
    - 2
    - 2
  embeddings_dim: 2
optimizer:
  type: torch.optim.Adam
  lr: 0.0005
loss_function:
  type: utils.nn.modules.VAELoss
  weights:
    - 500.0
    - 1.0
training:
  num_epochs: 3
